name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install development headers
      run: sudo apt install libsodium-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_FLAGS="-g -fmax-errors=1" -DBUILD_BLS_PYTHON_BINDINGS=false

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Debug build
        path: ${{github.workspace}}/build/chia_plot

  build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install development headers
      run: sudo apt install libsodium-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -D CMAKE_CXX_FLAGS="-O3 -fmax-errors=1" -DBUILD_BLS_PYTHON_BINDINGS=false

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Release build
        path: ${{github.workspace}}/build/chia_plot
